name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install pnpm
        run: npm install -g pnpm@10.14.0
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Run lint
        run: |
          echo "=== Current directory ==="
          pwd
          echo "=== Directory structure ==="
          ls -la
          echo "=== ESLint config ==="
          cat .eslintrc.json | head -20
          echo "=== Running lint with explicit packages path ==="
          npx eslint packages --ext .ts,.tsx,.js,.jsx --max-warnings 250
      
      - name: Run type check
        run: pnpm typecheck
      
      - name: Build core package
        run: |
          cd packages/core
          pnpm build
          echo "=== Checking core package dist folder ==="
          ls -la dist/ || echo "No dist folder"
          echo "=== Checking for .d.ts files ==="
          find dist -name "*.d.ts" 2>/dev/null || echo "No .d.ts files found"
      
      - name: Build packages
        run: |
          pnpm build
          echo "=== Checking all packages for .d.ts files ==="
          for pkg in core react-adapter svelte-adapter vue-adapter; do
            echo "--- Package: $pkg ---"
            ls -la packages/$pkg/dist/*.d.ts 2>/dev/null || echo "No .d.ts files in $pkg"
          done
      
      - name: Run tests
        run: pnpm test
      
      - name: Check package sizes
        run: pnpm size

  test-examples:
    name: Test Examples
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      
      - name: Install pnpm
        run: npm install -g pnpm@10.14.0
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Build core packages
        run: pnpm build
      
      - name: Build React example
        working-directory: examples/react-example
        run: pnpm build
      
      - name: Build Vue example
        working-directory: examples/vue-example
        run: pnpm build
      
      - name: Build Svelte example
        working-directory: examples/svelte-example
        run: pnpm build
      
      - name: Build Svelte 5 Runes example
        working-directory: examples/svelte5-runes-example
        run: pnpm build

  docs:
    name: Build Documentation
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      
      - name: Install pnpm
        run: npm install -g pnpm@10.14.0
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Build documentation
        run: pnpm docs:build