name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.14.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Link packages
        run: pnpm -r --filter='./packages/*' exec pnpm link --global && pnpm -r --filter='./packages/*' exec pnpm link --global @northprint/duckdb-wasm-adapter-core

      - name: Build core package
        run: |
          cd packages/core
          pnpm build
          echo "=== Checking core package dist folder ==="
          ls -la dist/ || echo "No dist folder"
          echo "=== Checking for .d.ts files ==="
          find dist -name "*.d.ts" 2>/dev/null || echo "No .d.ts files found"
          echo "=== Checking package.json types field ==="
          cat package.json | grep -A2 -B2 '"types"'

      - name: Build packages
        run: |
          pnpm build
          echo "=== Checking all packages for .d.ts files ==="
          for pkg in core react-adapter svelte-adapter vue-adapter; do
            echo "--- Package: $pkg ---"
            ls -la packages/$pkg/dist/*.d.ts 2>/dev/null || echo "No .d.ts files in $pkg"
          done

      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm release
          version: pnpm version
          commit: "chore: version packages"
          title: "chore: version packages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}