name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write
  issues: write
  packages: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.14.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile
          echo "=== Verifying build scripts ==="
          for pkg in core react-adapter vue-adapter svelte-adapter; do
            echo "--- $pkg build script ---"
            grep '"build"' packages/$pkg/package.json || echo "Build script not found"
          done

      - name: Build packages
        run: |
          pnpm build
          echo "=== Checking all packages for .d.ts files ==="
          for pkg in core react-adapter svelte-adapter vue-adapter; do
            echo "--- Package: $pkg ---"
            ls packages/$pkg/dist/*.d.ts 2>/dev/null | head -5 || echo "No .d.ts files in $pkg"
          done

      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm release
          version: pnpm version
          commit: "chore: version packages"
          title: "chore: version packages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}